### PR TITLE
make python shebang more portable

### PR DESCRIPTION
**Pull request by nicknovitski**
I use a weird distro that doesn't bother creating `/usr/bin/python`. I've checked, and both debian and ubuntu provide `/usr/bin/python2.7`, so I thought that might be more useful. And I did the `/usr/bin/env` trick because I always do that by default.  What do you think?

### CODE REVIEW

**Comment by phongvcao** [comment]
First I have to say that I won't be able to merge your Pull Request because you made the Pull Request on this [vim-scripts/vim-stardict](https://github.com/vim-scripts/vim-stardict) repo which I don't have "write access" to. This vim-scripts repo is only a mirror of the original vim-stardict repository, and owner like me do not have "write access" to this mirror.

What you should have done (and I will create a CONTRIBUTING.md in the next commit) is to create the Pull Request to `vim-stardict` official repository at [phongvcao/vim-stardict](https://github.com/phongvcao/vim-stardict) instead.

I think `/usr/bin/env python` trick is not a very good idea because AFAIK, in some Fedora releases, `env` is not placed under `/usr/bin` (but instead `/usr/local/bin` or `/bin`). So compability-wise, `/usr/bin/python` and `/usr/bin/env python` are practically equal.

`/usr/bin/env python2.7` is also not a very good idea because python2.7 is not installed in Arch Linux (a quite popular distro) by default.

Also, it seems to me that you wanted to change the shebang because you were using this plugin's bindings on your Bash/Zsh shell. If so, I am just gonna add an optional `STARDICT_PYTHON_PATH` variable that specifies the default python path that the user wants to execute `stardict.py` with.

**Comment by phongvcao** [comment]
@nicknovitski I have made the changes mentioned in my above comment on the official [phongvcao/vim-stardict](https://github.com/phongvcao/vim-stardict) repo. Please update your vim-stardict plugin to the latest version and export the python path that you want to use to the STARDICT_PYTHON_PATH environment variable (See the new README.md file for more info). Thanks for your Pull Request.

**Comment by nicknovitski** [comment]
Whoops, sorry. I am downloading the plugin from _your_ repository, but somehow I failed to notice this wasn't it.

Also, I actually use Arch! I happened to have python 2.7 installed, but not python 3. At any rate, I like the environment variable solution, and it works great for me, thank you for the change, and for noticing my issue.

**Comment by phongvcao** [comment]
@nicknovitski no problem. Hope you enjoy the plugin.

**Pull request closed without merging**
